# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171128_1014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skillset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
