# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171128_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset',
            name='profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(to='api.SkillSet'),
        ),
    ]
